services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: visitantes_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "5005:5000"
    environment:
      POSTGRES_DB: visitantes_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
      DB_HOST: db
    networks:
      - backend-net

volumes:
  db_data:

networks:
  backend-net:
